### PR TITLE
fix relative and absolute path bug

### PR DESCRIPTION
**Pull request by AlexStacker**

### CODE REVIEW

**Review by etylsarin — COMMENTED** [review]
hey mate, could you explain with an example, what situation are you trying to fix by these commits?

**Comment by AlexStacker** [comment]
I'm so sorry.
When I use the include directive with absolute path:
```
<!--#include file="/school/view/common/register.html"-->
```
It's can't resolve with nginx root path. When i set configure with root path,the relative path 
```
<!--#include file="login.html"-->
```
can't go to resolve.
It's very contradictory. so either I completely change the absolute path, or all change to the relative path.
The project is very old and big and I want to change with these commits quickly!Can you understand what I mean.

**Comment by etylsarin** [comment]
hey mate, wasn't sure about the proposed code changes. I've just updated the path construction logic, hope it fixes issues you mentioned.

**Comment by rmoskal** [comment]
This is still not working with either absolute or relative paths.  I'm not sure what the config actually accomplishes. And still I have to do some SSI replacement.

**Comment by etylsarin** [comment]
I'm closing this PR as there was a more recent update fixing the bug

**Pull request closed without merging**
